[project]
name = "building-energy-standards-data"
version = "0.3.1"
description = ""
readme = "README.md"
requires-python = ">=3.12,<=3.13"
authors = [
  { name = "Jeremy Lerond", email = "jeremy.lerond@pnnl.gov" },
  { name = "Weili Xu", email = "weili.xu@pnnl.gov" },
  { name = "Xuechen Lei", email = "xuechen.lei@pnnl.gov" },
  { name = "Lingzhe Wang", email = "lingzhe.wang@pnnl.gov" },
  { name = "Ammar Dehwah", email = "ammar.dehwah@pnnl.gov" },
  { name = "Julian Slane-Holloway", email = "julian.slane-holloway@pnnl.gov" },
]

dependencies = [
  "pytest>=7.4.3",
  "black==22.12.0",
]

[build-system]
requires = ["poetry-core>=2.3"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
agent = [
    "langchain>=1.2.7",
    "langchain-anthropic>=1.3.1",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.7",
    "automa-ai>=0.5.2",
    "dotenv>=0.9.9",
    "automa-ai>=0.5.2",
    "chromadb>=1.4.1",
    "datasets>=4.5.0",
    "dotenv>=0.9.9",
    "fastmcp>=3.1.1",
    "sqlglot>=30.6.0",
    "streamlit>=1.55.0"
]