[project]
name = "building-energy-standards-data"
version = "0.3.1"
description = "Database of building energy standards data for building energy simulation"
readme = "README.md"
requires-python = ">=3.10"
authors = [
  { name = "Jeremy Lerond", email = "jeremy.lerond@pnnl.gov" },
  { name = "Weili Xu", email = "weili.xu@pnnl.gov" },
  { name = "Xuechen Lei", email = "xuechen.lei@pnnl.gov" },
  { name = "Lingzhe Wang", email = "lingzhe.wang@pnnl.gov" },
  { name = "Ammar Dehwah", email = "ammar.dehwah@pnnl.gov" },
  { name = "Julian Slane-Holloway", email = "julian.slane-holloway@pnnl.gov" },
]

dependencies = [
  "pytest>=7.4.3",
  "black==22.12.0",
]

[build-system]
requires = ["poetry-core>=2.3"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
agent = [
    "langchain>=1.2.7",
    "langchain-anthropic>=1.3.1",
    "langchain-community>=0.4.1",
    "langchain-core>=1.2.7",
    "streamlit>=1.55.0"
]
dev = [
    "ty>=0.0.55",
]
